= Mequal -- Manifest Evaluation & Quality
:navtitle: Welcome

> In policy we trust!

== About

Mequal is a project based on the OPA policy engine with the goal of evaluating and validating SBOM manifests, giving feedback and guidance on the quality of a manifest, while also enabling easy custom policy authoring to extend the validation and evaluation criteria for context-specific manifests.

The future goals of this project are:

* *Validation and evaluation tooling* that can be easily integrated with SBOM manifest generation services.
* *Improve the quality* of a manifest by Generating reports to provide meaningful and actionable feedback and improvement suggestions.
* *Easy and extensible policy authoring* to enable Subject Matter Expertise to be reflected onto the quality assessment of a manifest.

For more information please visit our xref:project-goals:index.adoc[Project Goals] page.

== Try It Now!

include::getting-started:partial$quickstart.adoc[]

== Resources

* xref:getting-started:index.adoc[Getting Started]
* xref:project-goals:index.adoc[Project Goals]
* xref:writing-policies:index.adoc[Writing & Testing Policies]
* xref:policies:index.adoc[Mequal Policies]
* xref:handbook:index.adoc[Handbook]