FROM registry.access.redhat.com/ubi9/ubi@sha256:53d6c19d664f4f418ce5c823d3a33dbb562a2550ea249cf07ef10aa063ace38f

EXPOSE 8181
WORKDIR /home/mequal

RUN dnf install wget -y \
    && dnf install jq -y \
    && dnf install python -y \
    && wget https://github.com/open-policy-agent/opa/releases/download/v1.2.0/opa_linux_amd64 -O opa \
    && chmod +x ./opa \
    && wget https://github.com/enterprise-contract/ec-cli/releases/download/v0.6.159/ec_linux_amd64 -O ece \
    && chmod u+x ./ece \
    && mkdir ./bundle

RUN adduser -u 1000 -U mequal -m

USER root
COPY ./policy/ ./policy/
COPY ./hack/ ./hack/

# get prodsec external policies
RUN ./ece fetch policy -s github.com/project-ncl/mequal-prodsec-policies//policy/prodsec \
    && rm ./ece \
    && bash ./hack/annotations-generate.sh \
    && python ./hack/generate_bundle_info.py \
    && ./opa build -b $(ls -d -- ./policy/*/) -o ./bundle/mequal_policies.tar.gz
COPY ./container_files/cli-run.sh .
COPY ./container_files/server-run.sh .

RUN chown -R mequal:mequal /home/mequal

USER mequal
CMD ["/bin/bash", "./cli-run.sh"]