FROM registry.access.redhat.com/ubi9/ubi@sha256:53d6c19d664f4f418ce5c823d3a33dbb562a2550ea249cf07ef10aa063ace38f

ARG MANIFEST_REVISION=latest
EXPOSE 8181
WORKDIR /home/mequal

RUN dnf install wget -y \
    && dnf install jq -y \
    && dnf install python -y \
    && mkdir ./bundle

RUN adduser -u 1000 -U mequal -m

USER root
# only copy mequal and main bundles, the rest are external and should be fetched from the container itself
COPY ./policy/mequal/ ./policy/mequal/
COPY ./policy/main/ ./policy/main/
COPY ./scripts/ ./scripts/
COPY ./config/ ./config/

# get prodsec external policies
RUN bash ./scripts/manifest_revision.sh $MANIFEST_REVISION \
    && bash ./scripts/download-binaries.sh \
    && bash ./scripts/download-external-bundles.sh \
    && bash ./scripts/annotations-generate.sh \
    && python ./scripts/generate_bundle_info.py \
    && ./binaries/opa-cli build -b $(ls -d -- ./policy/*/) -o ./bundle/mequal_policies.tar.gz
COPY ./container_files/cli-run.sh .
COPY ./container_files/server-run.sh .

RUN chown -R mequal:mequal /home/mequal

USER mequal
CMD ["/bin/bash", "./cli-run.sh"]
