= Getting Started with Mequal

== 1. Quickstart with a Container

include::getting-started:partial$quickstart.adoc[]

== 2. Build and Run from Source Code

=== a. Build and Run Inside a Container (Recommended)

We can easily start editing the source code and maybe even adding some policies of our own without worrying about the tooling underneath.

[source,bash]
----
$ git clone https://github.com/project-ncl/mequal.git
$ cd mequal
$ podman build -t mequal -f ./container_files/Containerfile .
----

We can then either run Mequal as a CLI tool like below:

[source,bash]
----
$ cat input/good/sbom-example.json | podman run -i --rm mequal
----

Or we can run it as a server:

[source,bash]
----
podman run -p 8181:8181 -i --platform=linux/amd64 mequal /bin/bash ./server-run.sh
----

And then be able to make REST requests to it to query evaluation results:

[source,bash]
----
curl -X POST http://localhost:8181/v1/query -d '{ "query": "mequal=data.mequal.main;prodsec=data.prodsec.main" }" }' | jq
----

[TIP]
====
A playground is also available for testing out inputs and queries on the OPA server on `http://localhost:8181`
====

[TIP]
====
The {cli-run-script}[./container_files/cli-run.sh] or {server-run-script}[./container_files/server-run.sh] script can be edited to decide what should be ran inside the container. It can do evaluations using the OPA binary within it, running unit tests, change evaluation parameters, etc.
====

=== b. Run Policy Evaluation Locally

By running the script below, we can immediately start running our policy evaluations locally:

[source,bash]
----
$ bash ./hack/local-opa-run.sh
----

This script contains commands related to running policy evaluations or unit tests, and can be a reference for running policy evaluations. It can be used as a playground to test out different evaluation commands and parameters.

== 3. What are Policies? How do I Write Them?

For more information on what policies are and how to write them, please visit the xref:writing-policies:index.adoc[Writing & Testing Policies] section.

== 4. What Policies are Included in Mequal?

For more information on what policies come included with Mequal, please visit the xref:policies:index.adoc[Mequal Policies] section.