= Getting Started with Mequal

== 1. Quickstart with a Container

include::getting-started:partial$quickstart.adoc[]

== 2. Build and Run from Source Code

=== a. Build and Run Inside a Container (Recommended)

We can easily start editing the source code and maybe even adding some policies of our own without worrying about the tooling underneath.

[source,bash]
----
$ git clone https://github.com/project-ncl/mequal.git
$ cd mequal
$ podman build -t "mequal-testing" -f ./container_files/Containerfile .
$ cat input/good/sbom-example.json | podman run -i --rm mequal-testing
----

[TIP]
====
The https://google.com[./container_files/image-run.sh] script can be edited to decide what should be ran inside the container. Can decide to do evaluations using Conforma or using the OPA client embedded within it, running unit tests, change evaluation parameters, etc.
====

=== b. Run Policy Evaluation Locally

To run the policies locally, we'll need to use the https://github.com/enterprise-contract/ec-cli[Conforma CLI Tool], which is an OPA-based tool that does the policy evaluations inside the container. It also has the OPA CLI Tool embedded within it in case we want to do OPA evaluations, but we can also opt to download the https://github.com/open-policy-agent/opa[OPA CLI Tool separately from here] if we'd like to use a different OPA version.

[TIP]
====
Conforma formerly known as *Enterprise Contract* which is where the EC abbreviations in the code and documentation comes from. The download and use of these binaries can be fetched and used automatically using the https://google.com[./runme.sh] script in the repo.
====

Mequal currently relies on helper functions available from https://github.com/enterprise-contract/ec-policies[Conforma/EC policies] in order to generate better output from the policy evaluations and unit testing. *To run the policy evaluations successfully with OPA, we need to download these manually and put them in place.* This can already be done automatically using the https://google.com[./runme.sh] script in the repo. *For evaluation using Conforma/EC, these functions already fetched in the background, so it can immediately be used to start evaluating policies locally.*

By running the script mentioned above, we can immediate download the necessary binaries and helper functions, and start running our policy evaluations locally:

[source,bash]
----
$ bash ./runme.sh
----

The script contains commands related to running policy evaluations or unit tests, and can be a reference for running policy evaluations. It can be used as a playground to test out different evaluation commands and parameters.

== 3. What are Policies? How do I Write Them?

For more information on what policies are and how to write them, please visit the xref:writing-policies:index.adoc[Writing & Testing Policies] section.

== 4. What Policies are Included in Mequal?

For more information on what policies come included with Mequal, please visit the xref:policies:index.adoc[Mequal Policies] section.